name: CI

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dep
        run: npm install
    
  test:
    runs-on: ubuntu-latest

    steps:
      - run: npm install
      - run: npm test


      
